{{- if .Values.celery.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-celery
  labels:
    app.kubernetes.io/name: medinsight
    app.kubernetes.io/component: celery
spec:
  replicas: {{ .Values.celery.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: medinsight
      app.kubernetes.io/component: celery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: medinsight
        app.kubernetes.io/component: celery
    spec:
      containers:
        - name: celery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ toYaml .Values.celery.command | nindent 12 }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
{{- end }}
