apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app.kubernetes.io/name: medinsight
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: medinsight
    app.kubernetes.io/component: app
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
